### ISSUE TITLE
Create a checklist / runbook to prepare the robot and drive station for each match

### ISSUE THREAD

**Issue by bobtseattle** [robototes/InfiniteRecharge2020#16]
Includes documentation to

- [ ] Update robot software to the correct version
- [ ] Update the drive station software to the correct version
- [ ] Steps to test the drive station functionality
- [ ] Steps to test robot functionality
